const { launch, newPage, login, BASE } = require('./cms');
const db = (p) => fetch('http://127.0.0.1:9000/' + p + '.json?ns=pshop-music-default-rtdb', { headers: { Authorization: 'Bearer owner' } }).then(r => r.json());
(async () => { const b = await launch(); const { page, log } = await newPage(b);
  await login(page, 'admin@test.local');
  await page.goto(BASE + '/admin/banners.html'); await page.waitForTimeout(3000);
  await page.fill('#bTitle', 'TEST banner2'); await page.evaluate(() => { document.getElementById('bImage').value = 'https://example.com/b.jpg'; });
  await page.fill('#bLink', '/category.html'); await page.click('#bannerSaveBtn'); await page.waitForTimeout(1500);
  const bn = Object.values(await db('banners') || {}).find(x => x.title === 'TEST banner2');
  console.log('BANNER saved:', !!bn, 'active', bn && bn.active, 'zone', bn && bn.zone, '| ui', (await page.textContent('#bannerStatus')).trim(), '| errors', JSON.stringify(log.errors));
  const hp = await page.context().newPage(); await hp.goto(BASE + '/'); await hp.waitForTimeout(3500);
  console.log('HOME shows active banner img:', await hp.evaluate(() => !!document.querySelector('img[src="https://example.com/b.jpg"]')));
  await page.goto(BASE + '/admin/blog.html'); await page.waitForTimeout(3000);
  await page.fill('#postTitle', 'TEST blog 2'); await page.selectOption('#postStatus', 'published').catch(()=>{});
  await page.click('#postContentEditor .ql-editor'); await page.keyboard.type('Nội dung thật test');
  await page.click('#blogSaveBtn'); await page.waitForTimeout(1500);
  const p = Object.values(await db('blogPosts') || {}).find(x => x.title === 'TEST blog 2');
  console.log('BLOG contentHtml saved:', p && p.contentHtml, '| slug', p && p.slug);
  await hp.goto(BASE + '/blog.html'); await hp.waitForTimeout(3500); console.log('PUBLIC blog lists post:', (await hp.evaluate(() => document.body.innerText)).includes('TEST blog 2'));
  await hp.goto(BASE + '/blog-post.html?slug=' + (p && p.slug)); await hp.waitForTimeout(3500); console.log('PUBLIC post detail shows content:', (await hp.evaluate(() => document.body.innerText)).includes('Nội dung thật test'));
  console.log('errors', JSON.stringify(log.errors)); await b.close(); })();
