const { launch, newPage, login, BASE } = require('./cms');
const H = { headers: { Authorization: 'Bearer owner' } };
const db = p => fetch('http://127.0.0.1:9000/' + p + '.json?ns=pshop-music-default-rtdb', H).then(r => r.json());
(async () => { const b = await launch(); const { page, log } = await newPage(b); await login(page, 'editor@test.local');
 const R=(n,p,i)=>console.log((p?'PASS ':'FAIL ')+'[editor] '+n+(i?' | '+i:'')); const dialogs=[]; page.on('dialog',d=>dialogs.push(d.message().slice(0,60)));
 await page.goto(BASE + '/admin/sliders.html'); await page.waitForTimeout(3500);
 await page.evaluate(() => { const i = document.querySelector('#slideList input[type=text]'); i.value = 'EDITOR-SLIDE'; i.dispatchEvent(new Event('input', { bubbles: true })); i.dispatchEvent(new Event('change', { bubbles: true })); });
 await page.click('#saveSlidesBtn'); await page.waitForTimeout(2000);
 R('Slider lưu (siteContent/heroSlides)', JSON.stringify(await db('siteContent/heroSlides')).includes('EDITOR-SLIDE'));
 await page.goto(BASE + '/admin/categories.html'); await page.waitForTimeout(4500);
 const t0=JSON.stringify(await db('siteContent/categoryTiles'));
 await page.evaluate(()=>AdminCategories.moveTile(0,1)); await page.click('#saveTilesBtn'); await page.waitForTimeout(2000);
 const t1=JSON.stringify(await db('siteContent/categoryTiles')); R('Ô danh mục trang chủ lưu (categoryTiles)', t1!==t0);
 await page.evaluate(()=>AdminCategories.moveTile(0,1)); await page.click('#saveTilesBtn'); await page.waitForTimeout(1500);
 const m0=Object.keys(await db('siteContent/mediaAssets')||{}).length;
 await page.goto(BASE + '/admin/banners.html'); await page.waitForTimeout(3000);
 await page.click('#bImagePreview button.link-btn >> nth=0'); await page.waitForTimeout(1200);
 await page.setInputFiles('#medialibUploadInput', { name: 'editor.png', mimeType: 'image/png', buffer: require('fs').readFileSync(__dirname + '/big.png') });
 await page.waitForFunction(() => document.getElementById('bImage').value, null, { timeout: 15000 }).catch(() => {});
 await page.waitForTimeout(1500); const m1=Object.keys(await db('siteContent/mediaAssets')||{}).length;
 R('Media Library upload → form nhận URL + mediaAssets ghi', !!(await page.inputValue('#bImage')) && m1>m0, m0+'→'+m1);
 await page.goto(BASE + '/admin/products.html'); await page.waitForTimeout(5000);
 await page.evaluate(()=>AdminApp.editProduct('41')); await page.waitForTimeout(2500); const pr=(2000000+Math.floor(Math.random()*9999))+' ₫';
 await page.fill('#pPrice',pr); await page.click('#saveBtn'); await page.waitForTimeout(3000);
 R('Sản phẩm lưu', (await db('products/41')).price===pr);
 await page.goto(BASE + '/admin/menu.html'); await page.waitForTimeout(3500);
 R('trang Menu (admin-only) không cho editor', !page.url().endsWith('/admin/menu.html') || !(await page.$('#saveMenuBtn')), page.url().replace(BASE,''));
 R('không có dialog LƯU THẤT BẠI', !dialogs.some(d=>/THẤT BẠI/.test(d)), JSON.stringify(dialogs));
 console.log('errors', JSON.stringify(log.errors)); await b.close(); })();
